### ISSUE TITLE
Feature Request: Support apply commands smartly while triple clicking text, list and task items

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/obsidian-smarter-md-hotkeys#1]
**Feature Requested**

One can triple click to select an entire line of text, list and task items. When this action is applied, the hotkeys cannot take effect on the desired part of the text. Take the highlight command as an example:

- For the selected line of text, the highlight symbols would extend to the next empty line.
- For the selected line of list or task item, the highlight effect would include the item or task signifier.

Therefore, it would be great if the desired command would only be applied to the text part of the currently selected line.

**Relevant Screenshots**

This can be seen from the following screenshot:
<img width="370" alt="Screenshot 2021-11-20 at 15 21 16" src="https://user-images.githubusercontent.com/44930227/142729951-a78f495d-d660-4fea-9312-94fc06619763.png">

**Checklist**

- [x] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does the same thing.

**Comment by chrisgrieser** [comment]
I haven't even announced this plugin anywhere yet – where did you find it already? :P

Nevertheless, good find, thanks! Is fixed with the latest release.

**Comment by wenlzhang** [comment]
Great! It works now.

The path to find this plugin: Obsidian Roundup > obsidian-extra-md-commands > All your repositories > obsidian-smarter-md-hotkeys :-)
