### ISSUE TITLE
Feature Request: Delete a word

### ISSUE THREAD

**Issue by kmaustral** [chrisgrieser/obsidian-smarter-md-hotkeys#10]
Thanks for this wonderful plugin. It really helps with Obsidian-craft. 

One element I miss from Dynalist and Workflowy was the capacity to blast a hashtag (ALT-enter). While we don't need to mirror that exactly, it would be useful to have a hotkey that could delete a word if the cursor is inside it (including a hashtag). This would be a wonderful pruning tool for the vault.

**Comment by chrisgrieser** [comment]
I like the idea and isn't too hard to implement given the feature set already existing.

Has been implemented in version 1.2 :)
