### ISSUE TITLE
[Bug]: Markdown syntax goes inside brackets

### ISSUE THREAD

**Issue by Aaron-Bopp** [chrisgrieser/obsidian-smarter-md-hotkeys#12]
### Bug Description

When a link is selected and toggle bold or italics command is used, the asterisks will go inside of the brackets instead of outside even though the brackets were included in the selection.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/48270139/148857095-68826459-d1b0-4f7f-9199-29d94cb6f927.png)
Immediately after using the command
![image](https://user-images.githubusercontent.com/48270139/148857114-36d0f806-8f50-4cff-abee-a7dc70bf86c8.png)
Similarily, when the whole line is selected 
![image](https://user-images.githubusercontent.com/48270139/148857063-0811d75f-996f-4661-9840-c13cc1492df2.png)
the brackets on the end are ignored
![image](https://user-images.githubusercontent.com/48270139/148857340-801fea07-dc7c-4e8b-8091-f6b79256205a.png)

### To Reproduce

1. Select text
2. Use smarter bold command

I only tested bold, italics, and comment. Commenting did not have the same issue.

Also, this might be in FR territory, but I think it's related. My intuition would say that using a smarter command in a link when no text is selected would always place the syntax outside the brackets. I can see the case for it not being that way for syntax that is allowed in links like round brackets, but for markdown syntax like asterisk, square bracket etc it will always break the link.

i.e using smarter bold in like this
![image](https://user-images.githubusercontent.com/48270139/148857884-1a484788-b066-402c-94b8-241563b19f86.png)
turns into this
![image](https://user-images.githubusercontent.com/48270139/148857939-4e52d600-5374-4d37-9e93-c07f5da8cdba.png)

### Obsidian Version

0.13.19

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur?

- [X] Source (Edit)
- [X] Live Preview

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Okay, the latest release fixes the first issue, markup is now always out *outside* the selection. (did this for the punctuation commands as well, since I do not want to make the commands too different from each other).

This also works when you have the cursor inside a one-word wikilink. Wikilinks with more than one word are far more tricky to implement, so it's definitely something for later. Could you open a separate FR for that? Thanks
