### ISSUE TITLE
Feature Request: Enclosing brackets outside formatted text

### ISSUE THREAD

**Issue by dummifiedme** [chrisgrieser/obsidian-smarter-md-hotkeys#20]
### Feature Requested

When I try to enclose selected text into brackets, I get the unexpected. I am not adding it as a bug, but rather an enhancement for the use case.

Example would be best to describe what I mean.

```
**This** is the text line
**(This** is the text line) `after enclosing with bracket, currently`
(**This** is the text line) `this is what is expected`
```

It is the same with italic or highlights too.

### Which editor are you using?

- [X] New Editor
- [X] Legacy Editor

### Checklist

- [X] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does what I want.
- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
thanks for pointing this out, fixed with the latest release!
