### ISSUE TITLE
[Bug]: Smart highlight edge case

### ISSUE THREAD

**Issue by dummifiedme** [chrisgrieser/obsidian-smarter-md-hotkeys#22]
### Bug Description

When trying to highlight a line with link at the end, it would put the `==` inside the square brackets.

`==It should be [[like this]]==` 

but

`==It is [[like this==]]`

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/68785729/152082049-8c1eebcf-c9ea-41db-887a-c8a374a7555b.png)

### To Reproduce

Mark highlight just as you normally do, buthave a link towards the end of the selection. (Maybe at the start too)

### Obsidian Version

0.13.23

### Which editor are you using?

- [X] New Editor
- [X] Legacy Editor

### In which mode(s) does the problem occur?

- [X] Source (Edit)
- [X] Live Preview

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
fixed, thanks for reporting!
