### ISSUE TITLE
[Bug]: Italicizing markdown link text breaks the link

### ISSUE THREAD

**Issue by pjeby** [chrisgrieser/obsidian-smarter-md-hotkeys#24]
### Bug Description

If you select the text `foo` in `[foo](bar)` and italicize, you get `*[foo]*(bar)` which breaks the link.  The `*` should be inside the `[]`.

### To Reproduce

As given above

### Obsidian Version

0.13.23

### Which editor are you using?

- [X] New Editor

### In which mode(s) does the problem occur?

- [X] Source (Edit)
- [X] Live Preview

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
fixed in 1.6.1
