### ISSUE TITLE
Feature Request: Icons for Advanced Mobile Toolbar

### ISSUE THREAD

**Issue by jakejinglez** [chrisgrieser/obsidian-smarter-md-hotkeys#27]
### Feature Requested

Right now, all features appear with a generic ? icon in Advanced Mobile Toolbar. Makes them unusable on mobile. 

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does what I want.
- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
[The Advanced Mobile Toolbar allows you to set custom icons though?](https://github.com/phibr0/obsidian-advanced-toolbar#custom-icons)

**Comment by AngelusDomini** [comment]
I think what OP meant was to have these icons pre-set after installing the plugin. Some plugins do this, like Advanced Tables, icons are already set for some commands:

![|1242x1922, 20%](https://user-images.githubusercontent.com/59588053/169033902-9ebff330-22fa-436e-8539-e3f50e27b01d.png)
