### ISSUE TITLE
Feature Request: New Command -> Copy Relative Folder Path

### ISSUE THREAD

**Issue by FelipeRearden** [chrisgrieser/obsidian-smarter-md-hotkeys#28]
### Feature Requested

Hello @chrisgrieser !!!!

My FR is simple to explain: new command to that copy the **Folder Path** of the Active Note to the clipboard :)

### My Workflow

I wanna use this new command with the native `Search All Files` when I wanna execute a search only applied to files in the active folder.
- Since Shell Commands Plugin is not available on Mobile yet, I need a new way to do this on mobile 🙏

--- 

Thanks for reading this !!!!

I wish you a fantastic day 🌞

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does what I want.
- [X] The feature would be useful to more users than just me.

**Comment by FelipeRearden** [comment]
Hello @chrisgrieser !!!!

Sorry to bother you :)

I really appreciate if you could give me a feedback about this FR when you have some time :)

Thanks and have a great day !!!!

**Comment by chrisgrieser** [comment]
Hi! The suggested feature seems useful to me.

Only problem is, I have so much stuff to maintain (+ my day job 😅 ) that it sometimes takes a while until I can get to implementing issues, sorry! 🙏 

When I get back to working on this plugin, I'll keep this one in mind

**Comment by FelipeRearden** [comment]
> Hi! The suggested feature seems useful to me.

💙

> Only problem is, I have so much stuff to maintain (+ my day job 😅 ) that it sometimes takes a while until I can get to implementing issues, sorry! 🙏 

I 100% understand. I just wanna know if this FR is/was something that you willing to do or not. 
- This way I know if I have to keep looking for an alternative or not :)

> When I get back to working on this plugin, I'll keep this one in mind

Thank you very much for you reply and for considering this for  future versions!

**Comment by chrisgrieser** [comment]
yeah problem is simply that I have a bit too many plugins/themes/Alfred workflows 😅 

I simply do not have the time to implement all issues, let alone respond to them, even though I'd like to.

So looking for an alternative wouldn't be hurt, either 🙏

**Comment by FelipeRearden** [comment]
> yeah problem is simply that I have a bit too many plugins/themes/Alfred workflows 😅 

Yeah I know that you have a lot workflows to deal with. 

We step each other in many plug-in FR like AQS, VC, Advanced Cursors, Shell Commands and many others :)

This is the first time that I create an FR from one of your plugins and I just wanna take this opportunity to say that I really appreciate everything that you have been doing for our community 🙏 

You are a joy for our community and I know that I don't talk on Discord (because I don't know how to write in English very well) but I learn a lot reading your posts and comments. 

Many of the improvements that I do on many of my workflows has one piece of content that came from some idea that you share.

Thank you very much @chrisgrieser for everything !!!!!!!!

> So looking for an alternative wouldn't be hurt, either 🙏 

Okay 👍 I let you know when I found some alternative that works on mobile and then I close this issue.

**Comment by chrisgrieser** [comment]
thanks, I appreciate it 💙

You should also participate in Discord, your English looks fine to me and your FRs are always useful 🙂

**Comment by FelipeRearden** [comment]
I will into small steps 🪜 :)

And thank for your comment about my FRs, means a lot to me 

Have a great day!

**Comment by chrisgrieser** [comment]
implemented in last version – press the hotkey for copying the file path *three* times to get the parent folder path 👍

**Comment by FelipeRearden** [comment]
Working perfect on version `1.9.2` on Obsidian `0.14.6` 

Thank you very much @chrisgrieser 💙 💙 💙
