### ISSUE TITLE
Feature Request: Way to trigger two (or more) of these "smarter" hotkeys at once (i.e. macros)?

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/obsidian-smarter-md-hotkeys#31]
### Feature Requested

I'm having trouble using the macro plugin in nested vaults, so I was playing around with the idea of trigger multiple of these "smarter" hotkeys at once, e.g. `**bold**` and then `**==bold&highlighted==**. 

But I don't understand the syntax in the hotkey file, so I'm not sure if this is possible? 

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does what I want.
- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
The way the plugin works, it is unfortunately not possible to combine them with macros. However, if you simply want to use the Multi-Color-Highlights from Shimmering Focus, I added two new commands for that to the plugin 🙂

**Comment by ReaderGuy42** [comment]
Awesome, thank you! Which heading in Style Settings are these new commands under?

**Comment by chrisgrieser** [comment]
it's this plugin, not the style settings
<img width="1031" alt="Pasted image  2022-05-02 16 36 33" src="https://user-images.githubusercontent.com/73286100/166252838-d10cb59e-7ceb-4fe8-9d0a-f70b5171d2f1.png">

**Comment by ReaderGuy42** [comment]
Oh sorry, I misread that, but this is even cooler, thanks! However, even though the plugin just updated, I can't find those things from your screenshot. 
Is that in the hotkeys settings?

**Comment by ReaderGuy42** [comment]
Oh, that's fantastic! Thank you so much :)
