### ISSUE TITLE
Feature Request: A dataview inline field case

### ISSUE THREAD

**Issue by dummifiedme** [chrisgrieser/obsidian-smarter-md-hotkeys#32]
### Feature Requested

While the plugin works amazingly well, there is a need for a small correction for a special case.

In dataview inline fields, the Key and Value are expressed as `Key:: Value`. 

If I wish to add a bold or italic to the key, with the plugin, it results in `*Key:*: Value` instead of `*Key*:: Value`. 
It messes up the field. 

If its possible, can this special case be improved?

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does what I want.
- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
thanks, is fixed
