### ISSUE TITLE
Feature Request: Smarter Follow Link

### ISSUE THREAD

**Issue by andweeb** [chrisgrieser/obsidian-smarter-md-hotkeys#37]
### Feature Requested

First off thanks for this plugin @chrisgrieser! I've been using these hotkeys quite extensively :)

I'm thinking it would be nice to have a smarter hotkey for following a link. Following links in edit mode with the native "Follow link under cursor" hotkey are unfortunately a bit clunky and inconsistent, seemingly depending on text before the link, for example:
```md
## Markdown Example
[[Internal Link]] 
^ %% hotkey on any character in this line will follow the link %%

## [[Internal Link|Internal Link Header]] 
    ^ %% hotkey on the `[` characters will result in a no-op %%

* [[Internal Link|Internal link bullet point]] 
  ^ %% hotkey on the `[` characters will result in a no-op %%

[Obsidian](https://obsidian.md) is my second brain
^ %% hotkey on any character in the markup will follow the link %%

My second brain is on [Obsidian](https://obsidian.md)
                      ^ %% hotkey on the `[` character will result in a no-op %%
```

So with that said, I'm requesting a "Smarter Follow Link" feature that has the following behavior upon hotkey press:
1. Follow the link when the cursor is on **any part of an internal link markup**
2. Follow the link when the cursor is on **any part of an external link markup**
3. Follow the link when the cursor is on **any part of a line** when there it contains a **single link**
4. Follow **the closest link** to wherever the cursor is when there is **more than one link** on the given line
5. Follow **all external links** that are visually selected

The latter three behaviors might be debatable, as those are something I would want personally, but I'm open to discussion. I may also be open to trying my hand at implementing these.

Let me know what you think!

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does what I want.
- [X] The feature would be useful to more users than just me.

**Comment by andweeb** [comment]
These changes turned out to be easier than I thought!

I put up a PR at #38 that implements all the aforementioned behaviors, feel free to let me know whether there should be any tweaks or whether this command even makes sense for this plugin. Thanks!

**Comment by chrisgrieser** [comment]
closing this, see the comment at PR #38
