### ISSUE TITLE
[Bug]: does not work while editing a kanban plugin's card

### ISSUE THREAD

**Issue by KraXen72** [chrisgrieser/obsidian-smarter-md-hotkeys#49]
### Bug Description

while editing a card in mgmeyers' kanban plugin, `smarter markdown bold` and `smarter markdown italic` hotkeys don't work.

### Relevant Screenshot

---

### To Reproduce

1. make a kanban board
2. with `Shift` + `Enter` add some new lines
3. type in some text
4. try hitting your hotkey for `smarter markdown bold` and `smarter markdown italic`

### Obsidian Version

1.1.9

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur?

- [X] Source (Edit)
- [X] Live Preview

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
That one is actually a limitation of the Kanban plugin, not this plugin. You will notice any other hotkey plugin also does not work inside Kanban cards, which is also regularly annoying me :(

**Comment by KraXen72** [comment]
is it possible to move this issue to the Kanban plugin repo or do i just copy and paste there

**Comment by chrisgrieser** [comment]
I don't think you can move issues, but there should already be some issues about that problem where you can comment
