### ISSUE TITLE
Feature Request: Better support for applying hotkeys on header items

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/obsidian-smarter-md-hotkeys#8]
It would be great if hotkeys can be applied properly when selecting header items by triple-clicking to select the entire line.

Current effect:

`==## Header level 1==`

Desired effect:

`## ==Header level 1==`

**Comment by chrisgrieser** [comment]
good idea! haven't thought about this since I do not apply markup to headings usually, but for highlights it can make sense.

Luckily, this was easy to implement since I could simply add heading-syntax to the function that trims stuff at the beginning of the selection :)

Should work in 0.13.5!
